analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    constant_identifier_names: ignore
    require_trailing_commas: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/generated/**"
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
