name: boilerplate_app
description: boilerplate
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  retrofit: ^4.4.1
  shared_preferences: ^2.5.1
  toolkit:
    path: "./packages/toolkit"
  uikit:
    path: "./packages/uikit"

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/launch_image/

scripts: derry.yaml
