name: boilerplate_app
description: boilerplate
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  retrofit: ^4.4.2
  shared_preferences: ^2.3.3
  toolkit:
    path: "./packages/toolkit"
  uikit:
    path: "./packages/uikit"

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  retrofit_generator: ^9.1.5
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/launch_image/

scripts: derry.yaml
